[package]
name = "monitor_sistema"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.28"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
sysinfo = "0.29.10"
tokio = { version = "1.32.0", features = ["full"] }
tokio-tungstenite = "0.20.0"
